import { useEffect, useMemo, useRef, useState } from "react";
import { getOpticProfiles, saveOpticProfiles } from "@/lib/db";
import type { OpticProfile } from "@/lib/types";
import { calculateReticleOffset, calculateZeroClicks, type AngularUnit, type DistanceUnit, type HorizontalDirection, type OffsetUnit, type ReticleOffsetResult, type ReticleType, type VerticalDirection, type ZeroingResult } from "@/lib/zeroing";

type CorrectionForm = { distance: string; distanceUnit: DistanceUnit; opticUnit: AngularUnit; elevationPerClick: string; windagePerClick: string; verticalMagnitude: string; verticalUnit: OffsetUnit; verticalDirection: VerticalDirection; horizontalMagnitude: string; horizontalUnit: OffsetUnit; horizontalDirection: HorizontalDirection };
type ReticleForm = { distance: string; distanceUnit: DistanceUnit; reticleUnit: AngularUnit; horizontalMagnitude: string; horizontalDirection: HorizontalDirection; verticalMagnitude: string; verticalDirection: VerticalDirection; reticleType: ReticleType; calibrationMagnification: string; currentMagnification: string };

const initialCorrection: CorrectionForm = { distance: "100", distanceUnit: "yards", opticUnit: "MOA", elevationPerClick: "0.5", windagePerClick: "0.5", verticalMagnitude: "4", verticalUnit: "inches", verticalDirection: "LOW", horizontalMagnitude: "3", horizontalUnit: "inches", horizontalDirection: "LEFT" };
const initialReticle: ReticleForm = { distance: "100", distanceUnit: "yards", reticleUnit: "MIL", horizontalMagnitude: "1.5", horizontalDirection: "LEFT", verticalMagnitude: "0.8", verticalDirection: "LOW", reticleType: "FFP", calibrationMagnification: "10", currentMagnification: "5" };
const n = (value: string) => { const parsed = Number(value); return value.trim() !== "" && Number.isFinite(parsed) ? parsed : undefined; };
const fixed = (value: number, decimals = 2) => Number.isFinite(value) ? value.toFixed(decimals) : "—";
const unitLabel = (unit: AngularUnit) => unit === "MOA" ? "MOA" : "mil";

export default function Zeroing() {
  const [correction, setCorrection] = useState(initialCorrection);
  const [reticle, setReticle] = useState(initialReticle);
  const [zeroResult, setZeroResult] = useState<ZeroingResult | null>(null);
  const [reticleResult, setReticleResult] = useState<ReticleOffsetResult | null>(null);
  const [correctionError, setCorrectionError] = useState("");
  const [reticleError, setReticleError] = useState("");
  const [profiles, setProfiles] = useState<OpticProfile[]>([]);
  const [profileName, setProfileName] = useState("");
  const correctionRef = useRef<HTMLElement>(null);

  useEffect(() => { void getOpticProfiles().then(setProfiles); }, []);

  const setC = <K extends keyof CorrectionForm>(key: K, value: CorrectionForm[K]) => setCorrection(current => ({ ...current, [key]: value }));
  const setR = <K extends keyof ReticleForm>(key: K, value: ReticleForm[K]) => setReticle(current => ({ ...current, [key]: value }));
  const clickOptions = correction.opticUnit === "MOA" ? ["0.25", "0.5", "1"] : ["0.05", "0.1", "0.2"];

  const calculateCorrection = () => {
    const distance = n(correction.distance); const elevationPerClick = n(correction.elevationPerClick); const windagePerClick = n(correction.windagePerClick);
    const vertical = n(correction.verticalMagnitude); const horizontal = n(correction.horizontalMagnitude);
    if (!distance || distance <= 0) return setCorrectionError("Enter a target distance greater than zero.");
    if (!elevationPerClick || elevationPerClick <= 0 || !windagePerClick || windagePerClick <= 0) return setCorrectionError("Enter positive elevation and windage click values.");
    if (vertical !== undefined && vertical < 0 || horizontal !== undefined && horizontal < 0) return setCorrectionError("Offset magnitudes cannot be negative.");
    setCorrectionError("");
    setZeroResult(calculateZeroClicks({ distance, distanceUnit: correction.distanceUnit, opticUnit: correction.opticUnit, elevationPerClick, windagePerClick, vertical: { magnitude: vertical, unit: correction.verticalUnit, direction: correction.verticalDirection }, horizontal: { magnitude: horizontal, unit: correction.horizontalUnit, direction: correction.horizontalDirection } }));
  };

  const calculateReticle = () => {
    const distance = n(reticle.distance); const horizontal = n(reticle.horizontalMagnitude); const vertical = n(reticle.verticalMagnitude); const calibration = n(reticle.calibrationMagnification); const current = n(reticle.currentMagnification);
    if (!distance || distance <= 0) return setReticleError("Enter a target distance greater than zero.");
    if (horizontal === undefined && vertical === undefined) return setReticleError("Enter a horizontal or vertical reticle measurement.");
    if (horizontal !== undefined && horizontal < 0 || vertical !== undefined && vertical < 0) return setReticleError("Reticle measurements cannot be negative.");
    if (reticle.reticleType === "SFP" && (!calibration || calibration <= 0 || !current || current <= 0)) return setReticleError("SFP scopes need positive calibration and current magnifications.");
    setReticleError("");
    setReticleResult(calculateReticleOffset({ distance, distanceUnit: reticle.distanceUnit, reticleUnit: reticle.reticleUnit, reticleType: reticle.reticleType, calibrationMagnification: calibration, currentMagnification: current, horizontal: { magnitude: horizontal, direction: reticle.horizontalDirection }, vertical: { magnitude: vertical, direction: reticle.verticalDirection } }));
  };

  const transferToZeroing = () => {
    if (!reticleResult) return;
    setCorrection(current => ({ ...current, distance: reticle.distance, distanceUnit: reticle.distanceUnit, verticalMagnitude: reticleResult.vertical.provided ? fixed(reticleResult.vertical.inches) : "", verticalUnit: "inches", verticalDirection: reticleResult.vertical.direction as VerticalDirection, horizontalMagnitude: reticleResult.horizontal.provided ? fixed(reticleResult.horizontal.inches) : "", horizontalUnit: "inches", horizontalDirection: reticleResult.horizontal.direction as HorizontalDirection }));
    setZeroResult(null); setCorrectionError(""); correctionRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  const saveProfile = async () => {
    const elevation = n(correction.elevationPerClick); const windage = n(correction.windagePerClick); const name = profileName.trim();
    if (!name || !elevation || elevation <= 0 || !windage || windage <= 0) return;
    const next: OpticProfile = { id: crypto.randomUUID(), name, unit: correction.opticUnit, elevationPerClick: elevation, windagePerClick: windage, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() };
    const nextProfiles = [...profiles.filter(profile => profile.name.toLowerCase() !== name.toLowerCase()), next]; setProfiles(nextProfiles); setProfileName(""); await saveOpticProfiles(nextProfiles);
  };
  const loadProfile = (id: string) => { const profile = profiles.find(item => item.id === id); if (!profile) return; setCorrection(current => ({ ...current, opticUnit: profile.unit, elevationPerClick: String(profile.elevationPerClick), windagePerClick: String(profile.windagePerClick) })); setZeroResult(null); };
  const deleteProfile = async (id: string) => { const next = profiles.filter(profile => profile.id !== id); setProfiles(next); await saveOpticProfiles(next); };

  return <>
    <PageHeader eyebrow="ZEROING / OPTIC TOOLS" title="Put the rounds on zero" note="Fast, range-ready corrections for optic turrets and reticle measurements." />
    <div className="zeroing-tabs" aria-label="Zeroing tools"><a href="#zeroing-correction">Correction</a><a href="#reticle-offset">Reticle offset</a></div>
    <div className="zeroing-grid">
      <section className="zeroing-card" id="zeroing-correction" ref={correctionRef}>
        <div className="tool-heading"><div><span className="tool-kicker">01 / TURRET CLICKS</span><h2>Zeroing Correction</h2><p>Turn the measured impact into the optic adjustment required.</p></div><span className="tool-icon">⌾</span></div>
        <div className="zeroing-fields">
          <div className="field-group"><label>Distance to target</label><div className="input-pair"><input aria-label="Distance to target" type="number" min="0.01" step="any" inputMode="decimal" value={correction.distance} onChange={event => setC("distance", event.target.value)} /><select aria-label="Distance unit" value={correction.distanceUnit} onChange={event => setC("distanceUnit", event.target.value as DistanceUnit)}><option value="yards">yards</option><option value="meters">meters</option></select></div></div>
          <div className="field-group"><label>Optic adjustment</label><div className="adjustment-grid"><div className="unit-toggle" role="group" aria-label="Optic measurement system"><button type="button" className={correction.opticUnit === "MOA" ? "selected" : ""} onClick={() => setC("opticUnit", "MOA")}>MOA</button><button type="button" className={correction.opticUnit === "MIL" ? "selected" : ""} onClick={() => setC("opticUnit", "MIL")}>MRAD / MIL</button></div><div className="click-inputs"><label>Elevation / click<input type="number" min="0.0001" step="any" inputMode="decimal" value={correction.elevationPerClick} onChange={event => setC("elevationPerClick", event.target.value)} /></label><label>Windage / click<input type="number" min="0.0001" step="any" inputMode="decimal" value={correction.windagePerClick} onChange={event => setC("windagePerClick", event.target.value)} /></label></div><div className="quick-values"><span>Quick values</span>{clickOptions.map(value => <button type="button" key={value} onClick={() => { setC("elevationPerClick", value); setC("windagePerClick", value); }}>{value} {unitLabel(correction.opticUnit)}</button>)}</div></div></div>
          <fieldset className="offset-fieldset"><legend>Impact location</legend><p className="field-help">Use magnitude + direction. Never enter a negative number.</p><div className="offset-row"><div className="offset-axis"><b>Vertical</b><span>Elevation</span></div><input aria-label="Vertical offset magnitude" type="number" min="0" step="any" inputMode="decimal" placeholder="0" value={correction.verticalMagnitude} onChange={event => setC("verticalMagnitude", event.target.value)} /><select aria-label="Vertical offset unit" value={correction.verticalUnit} onChange={event => setC("verticalUnit", event.target.value as OffsetUnit)}><option value="inches">inches</option><option value="centimeters">cm</option><option value="MOA">MOA</option><option value="mil">mil</option></select><select aria-label="Vertical impact direction" value={correction.verticalDirection} onChange={event => setC("verticalDirection", event.target.value as VerticalDirection)}><option value="LOW">LOW</option><option value="HIGH">HIGH</option></select></div><div className="offset-row"><div className="offset-axis"><b>Horizontal</b><span>Windage</span></div><input aria-label="Horizontal offset magnitude" type="number" min="0" step="any" inputMode="decimal" placeholder="0" value={correction.horizontalMagnitude} onChange={event => setC("horizontalMagnitude", event.target.value)} /><select aria-label="Horizontal offset unit" value={correction.horizontalUnit} onChange={event => setC("horizontalUnit", event.target.value as OffsetUnit)}><option value="inches">inches</option><option value="centimeters">cm</option><option value="MOA">MOA</option><option value="mil">mil</option></select><select aria-label="Horizontal impact direction" value={correction.horizontalDirection} onChange={event => setC("horizontalDirection", event.target.value as HorizontalDirection)}><option value="LEFT">LEFT</option><option value="RIGHT">RIGHT</option></select></div></fieldset>
        </div>
        <ProfileBar profiles={profiles} profileName={profileName} setProfileName={setProfileName} saveProfile={saveProfile} loadProfile={loadProfile} deleteProfile={deleteProfile} />
        {correctionError && <p className="zeroing-error" role="alert">{correctionError}</p>}<button className="primary calculate-button" type="button" onClick={calculateCorrection}>Calculate correction</button>
        {zeroResult && <CorrectionResults result={zeroResult} distance={n(correction.distance) ?? 0} distanceUnit={correction.distanceUnit} opticUnit={correction.opticUnit} elevationPerClick={n(correction.elevationPerClick) ?? 0} windagePerClick={n(correction.windagePerClick) ?? 0} />}
      </section>

      <section className="zeroing-card" id="reticle-offset">
        <div className="tool-heading"><div><span className="tool-kicker">02 / IMPACT MEASUREMENT</span><h2>Reticle Offset</h2><p>Convert a reticle reading into physical point-of-aim to point-of-impact distance.</p></div><span className="tool-icon">⊕</span></div>
        <div className="zeroing-fields">
          <div className="field-group"><label>Distance to target</label><div className="input-pair"><input aria-label="Reticle distance" type="number" min="0.01" step="any" inputMode="decimal" value={reticle.distance} onChange={event => setR("distance", event.target.value)} /><select aria-label="Reticle distance unit" value={reticle.distanceUnit} onChange={event => setR("distanceUnit", event.target.value as DistanceUnit)}><option value="yards">yards</option><option value="meters">meters</option></select></div></div>
          <div className="field-group"><label>Reticle measurement</label><div className="unit-toggle" role="group" aria-label="Reticle measurement unit"><button type="button" className={reticle.reticleUnit === "MIL" ? "selected" : ""} onClick={() => setR("reticleUnit", "MIL")}>MIL</button><button type="button" className={reticle.reticleUnit === "MOA" ? "selected" : ""} onClick={() => setR("reticleUnit", "MOA")}>MOA</button></div></div>
          <fieldset className="offset-fieldset"><legend>Observed offset</legend><p className="field-help">One axis can be left blank.</p><div className="offset-row"><div className="offset-axis"><b>Horizontal</b><span>{reticle.reticleUnit} / windage</span></div><input aria-label="Observed horizontal offset" type="number" min="0" step="any" inputMode="decimal" placeholder="—" value={reticle.horizontalMagnitude} onChange={event => setR("horizontalMagnitude", event.target.value)} /><span className="unit-suffix">{unitLabel(reticle.reticleUnit)}</span><select aria-label="Observed horizontal direction" value={reticle.horizontalDirection} onChange={event => setR("horizontalDirection", event.target.value as HorizontalDirection)}><option value="LEFT">LEFT</option><option value="RIGHT">RIGHT</option></select></div><div className="offset-row"><div className="offset-axis"><b>Vertical</b><span>{reticle.reticleUnit} / elevation</span></div><input aria-label="Observed vertical offset" type="number" min="0" step="any" inputMode="decimal" placeholder="—" value={reticle.verticalMagnitude} onChange={event => setR("verticalMagnitude", event.target.value)} /><span className="unit-suffix">{unitLabel(reticle.reticleUnit)}</span><select aria-label="Observed vertical direction" value={reticle.verticalDirection} onChange={event => setR("verticalDirection", event.target.value as VerticalDirection)}><option value="LOW">LOW</option><option value="HIGH">HIGH</option></select></div></fieldset>
          <div className="field-group"><label>Reticle type</label><select value={reticle.reticleType} onChange={event => setR("reticleType", event.target.value as ReticleType)}><option value="FFP">FFP — First Focal Plane</option><option value="SFP">SFP — Second Focal Plane</option><option value="unknown">Unknown / not applicable</option></select></div>
          {reticle.reticleType === "SFP" && <div className="click-inputs magnification-fields"><label>Calibration magnification<input type="number" min="0.01" step="any" inputMode="decimal" value={reticle.calibrationMagnification} onChange={event => setR("calibrationMagnification", event.target.value)} placeholder="10x" /></label><label>Current magnification<input type="number" min="0.01" step="any" inputMode="decimal" value={reticle.currentMagnification} onChange={event => setR("currentMagnification", event.target.value)} placeholder="5x" /></label></div>}
        </div>
        {reticle.reticleType === "FFP" && <p className="info-note">FFP measurements remain valid at any magnification.</p>}{reticle.reticleType === "SFP" && <p className="info-note">SFP readings are scaled relative to the calibration magnification.</p>}
        {reticleError && <p className="zeroing-error" role="alert">{reticleError}</p>}<button className="primary calculate-button" type="button" onClick={calculateReticle}>Calculate physical offset</button>
        {reticleResult && <ReticleResults result={reticleResult} distance={n(reticle.distance) ?? 0} distanceUnit={reticle.distanceUnit} reticleUnit={reticle.reticleUnit} reticleType={reticle.reticleType} onTransfer={transferToZeroing} />}
      </section>
    </div>
    <details className="quick-reference"><summary>Quick Reference</summary><div><p><b>At 100 yards</b><br />1 MOA ≈ 1.047"<br />0.5 MOA ≈ 0.524"<br />1 MIL = 3.6"<br />0.1 MIL = 0.36"</p><p><b>At 100 meters</b><br />1 MIL = 10 cm<br />0.1 MIL = 1 cm</p></div></details>
  </>;
}

function PageHeader({ eyebrow, title, note }: { eyebrow: string; title: string; note: string }) { return <header className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{note}</p></div></header>; }

function ProfileBar({ profiles, profileName, setProfileName, saveProfile, loadProfile, deleteProfile }: { profiles: OpticProfile[]; profileName: string; setProfileName: (value: string) => void; saveProfile: () => Promise<void>; loadProfile: (id: string) => void; deleteProfile: (id: string) => Promise<void> }) { return <details className="profile-bar"><summary>Saved optic profiles <span>{profiles.length}</span></summary><div className="profile-content">{profiles.length > 0 && <div className="profile-list">{profiles.map(profile => <div className="profile-row" key={profile.id}><button type="button" onClick={() => loadProfile(profile.id)}><b>{profile.name}</b><small>{profile.elevationPerClick} {unitLabel(profile.unit)} / click{profile.windagePerClick !== profile.elevationPerClick ? ` · windage ${profile.windagePerClick}` : ""}</small></button><button type="button" aria-label={`Delete ${profile.name}`} onClick={() => { void deleteProfile(profile.id); }}>×</button></div>)}</div>}<div className="profile-save"><input aria-label="Optic profile name" placeholder="Profile name, e.g. LPVO" value={profileName} onChange={event => setProfileName(event.target.value)} /><button className="secondary" type="button" onClick={() => { void saveProfile(); }}>Save current settings</button></div></div></details>; }

function CorrectionResults({ result, distance, distanceUnit, opticUnit, elevationPerClick, windagePerClick }: { result: ZeroingResult; distance: number; distanceUnit: DistanceUnit; opticUnit: AngularUnit; elevationPerClick: number; windagePerClick: number }) { return <section className="correction-result"><div className="result-heading"><span>REQUIRED CORRECTION</span><small>{distance} {distanceUnit} · {unitLabel(opticUnit)} / click</small></div><div className="result-grid"><ResultAxis title="Elevation" result={result.elevation} perClick={elevationPerClick} /><ResultAxis title="Windage" result={result.windage} perClick={windagePerClick} /></div><TargetPlot elevation={result.elevation} windage={result.windage} /></section>; }
function ResultAxis({ title, result, perClick }: { title: string; result: ZeroingResult["elevation"]; perClick: number }) { return <div className="result-axis"><small>{title}</small><b className={result.provided ? "" : "muted-result"}>{result.provided ? `${result.recommendedClicks} CLICKS ${result.adjustmentDirection}` : "NO ADJUSTMENT REQUIRED"}</b>{result.provided && <div className="technical-result"><span>Impact: {fixed(result.angularOffset, 2)} {unitLabel(result.angularUnit)}</span><span>Exact: {fixed(result.exactClicks)} clicks · {perClick} / click</span><span>Residual: ~{fixed(result.residual)} {result.residualUnit} {result.residualDirection}</span></div>}</div>; }
function TargetPlot({ elevation, windage }: { elevation: ZeroingResult["elevation"]; windage: ZeroingResult["windage"] }) { const x = windage.provided ? windage.adjustmentDirection === "RIGHT" ? 70 : 30 : 50; const y = elevation.provided ? elevation.adjustmentDirection === "UP" ? 30 : 70 : 50; return <div className="target-plot" aria-label="Impact location diagram"><span className="target-ring ring-one" /><span className="target-ring ring-two" /><span className="target-center" /><span className="target-point" style={{ left: `${x}%`, top: `${y}%` }} /></div>; }
function ReticleResults({ result, distance, distanceUnit, reticleUnit, reticleType, onTransfer }: { result: ReticleOffsetResult; distance: number; distanceUnit: DistanceUnit; reticleUnit: AngularUnit; reticleType: ReticleType; onTransfer: () => void }) { return <section className="reticle-result"><div className="result-heading"><span>PHYSICAL IMPACT OFFSET</span><small>{distance} {distanceUnit} · {reticleUnit}{reticleType === "SFP" ? " · scaled" : ""}</small></div>{result.horizontal.provided && <ReticleAxis title="Horizontal" axis={result.horizontal} reticleUnit={reticleUnit} />}{result.vertical.provided && <ReticleAxis title="Vertical" axis={result.vertical} reticleUnit={reticleUnit} />}<button className="secondary use-zeroing" type="button" onClick={onTransfer}>Use for Zeroing</button></section>; }
function ReticleAxis({ title, axis, reticleUnit }: { title: string; axis: ReticleOffsetResult["horizontal"]; reticleUnit: AngularUnit }) { return <div className="reticle-axis"><div><small>{title}</small><b>{fixed(axis.angular, 2)} {unitLabel(reticleUnit)} {axis.direction}</b></div><strong>{fixed(axis.inches)}" {axis.direction}</strong><span>= {fixed(axis.centimeters)} cm {axis.direction}</span></div>; }
