import { useRef, useState } from "react";
import { calculateReticleOffset, calculateZeroClicks, type AngularUnit, type DistanceUnit, type HorizontalDirection, type OffsetUnit, type ReticleOffsetResult, type ReticleType, type VerticalDirection, type ZeroingResult } from "@/lib/zeroing";

type CorrectionForm = { distance: string; distanceUnit: DistanceUnit; opticUnit: AngularUnit; elevationPerClick: string; windagePerClick: string; verticalMagnitude: string; verticalUnit: OffsetUnit; verticalDirection: VerticalDirection; horizontalMagnitude: string; horizontalUnit: OffsetUnit; horizontalDirection: HorizontalDirection };
type ReticleForm = { distance: string; distanceUnit: DistanceUnit; reticleUnit: AngularUnit; horizontalMagnitude: string; horizontalDirection: HorizontalDirection; verticalMagnitude: string; verticalDirection: VerticalDirection; reticleType: ReticleType; magnification: string };
type Tool = "correction" | "impact";

const initialCorrection: CorrectionForm = { distance: "", distanceUnit: "yards", opticUnit: "MOA", elevationPerClick: "0.5", windagePerClick: "0.5", verticalMagnitude: "", verticalUnit: "inches", verticalDirection: "LOW", horizontalMagnitude: "", horizontalUnit: "inches", horizontalDirection: "LEFT" };
const initialReticle: ReticleForm = { distance: "", distanceUnit: "yards", reticleUnit: "MIL", horizontalMagnitude: "", horizontalDirection: "LEFT", verticalMagnitude: "", verticalDirection: "LOW", reticleType: "FFP", magnification: "" };
const QUICK_OPTIC_VALUES: { label: string; value: string; unit: "MOA" | "MIL" }[] = [{ label: "Rifle Optics (EXPS, ACRO, T2)", value: "0.5", unit: "MOA" }, { label: "Pistol Optics (RMR, SRO, DPP)", value: "1", unit: "MOA" }, { label: "MOA LPVOs — 1/2 MOA", value: "0.5", unit: "MOA" }, { label: "MRAD LPVOs — 0.2 MILs", value: "0.2", unit: "MIL" }, { label: "MOA MPVOs — 1/4 MOA", value: "0.25", unit: "MOA" }, { label: "MRAD MPVOs — 0.1 MIL", value: "0.1", unit: "MIL" }];
const n = (value: string) => { const parsed = Number(value); return value.trim() !== "" && Number.isFinite(parsed) ? parsed : undefined; };
const fixed = (value: number, decimals = 2) => Number.isFinite(value) ? value.toFixed(decimals) : "—";
const unitLabel = (unit: AngularUnit) => unit === "MOA" ? "MOA" : "mil";

export default function Zeroing() {
  const [correction, setCorrection] = useState(initialCorrection);
  const [reticle, setReticle] = useState(initialReticle);
  const [zeroResult, setZeroResult] = useState<ZeroingResult | null>(null);
  const [reticleResult, setReticleResult] = useState<ReticleOffsetResult | null>(null);
  const [correctionError, setCorrectionError] = useState("");
  const [reticleError, setReticleError] = useState("");
  const [activeTool, setActiveTool] = useState<Tool | null>(null);
  const [selectedOptic, setSelectedOptic] = useState("");
  const correctionRef = useRef<HTMLElement>(null);

  const setC = <K extends keyof CorrectionForm>(key: K, value: CorrectionForm[K]) => setCorrection(current => ({ ...current, [key]: value }));
  const setR = <K extends keyof ReticleForm>(key: K, value: ReticleForm[K]) => setReticle(current => ({ ...current, [key]: value }));

  const calculateCorrection = () => {
    const distance = n(correction.distance) ?? 100; const clickValue = n(correction.elevationPerClick); const elevationPerClick = clickValue; const windagePerClick = clickValue;
    const vertical = n(correction.verticalMagnitude) ?? 0; const horizontal = n(correction.horizontalMagnitude) ?? 0;
    if (!distance || distance <= 0) return setCorrectionError("Enter a target distance greater than zero.");
    if (!clickValue || clickValue <= 0) return setCorrectionError("Enter a positive click value.");
    if (vertical !== undefined && vertical < 0 || horizontal !== undefined && horizontal < 0) return setCorrectionError("Offset magnitudes cannot be negative.");
    setCorrectionError("");
    setZeroResult(calculateZeroClicks({ distance, distanceUnit: correction.distanceUnit, opticUnit: correction.opticUnit, elevationPerClick: clickValue, windagePerClick: clickValue, vertical: { magnitude: vertical, unit: correction.verticalUnit, direction: correction.verticalDirection }, horizontal: { magnitude: horizontal, unit: correction.horizontalUnit, direction: correction.horizontalDirection } }));
  };

  const calculateReticle = () => {
    const distance = n(reticle.distance) ?? 100; const horizontal = n(reticle.horizontalMagnitude) ?? 0; const vertical = n(reticle.verticalMagnitude) ?? 0; const magnification = n(reticle.magnification) ?? 6;
    if (!distance || distance <= 0) return setReticleError("Enter a target distance greater than zero.");
    if (horizontal !== undefined && horizontal < 0 || vertical !== undefined && vertical < 0) return setReticleError("Reticle measurements cannot be negative.");
    if (reticle.reticleType === "SFP" && (!magnification || magnification <= 0)) return setReticleError("SFP scopes need a positive maximum magnification.");
    setReticleError("");
    setReticleResult(calculateReticleOffset({ distance, distanceUnit: reticle.distanceUnit, reticleUnit: reticle.reticleUnit, reticleType: reticle.reticleType, calibrationMagnification: magnification, currentMagnification: magnification, horizontal: { magnitude: horizontal, direction: reticle.horizontalDirection }, vertical: { magnitude: vertical, direction: reticle.verticalDirection } }));
  };

  const transferToZeroing = () => {
    if (!reticleResult) return;
    setCorrection(current => ({ ...current, distance: String(n(reticle.distance) ?? 100), distanceUnit: reticle.distanceUnit, verticalMagnitude: reticleResult.vertical.provided ? fixed(reticleResult.vertical.inches) : "", verticalUnit: "inches", verticalDirection: reticleResult.vertical.direction as VerticalDirection, horizontalMagnitude: reticleResult.horizontal.provided ? fixed(reticleResult.horizontal.inches) : "", horizontalUnit: "inches", horizontalDirection: reticleResult.horizontal.direction as HorizontalDirection }));
    setZeroResult(null); setCorrectionError(""); correctionRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  const applyQuickOptic = (label: string) => { const optic = QUICK_OPTIC_VALUES.find(item => item.label === label); if (!optic) return; setSelectedOptic(label); setC("opticUnit", optic.unit); setC("elevationPerClick", optic.value); setC("windagePerClick", optic.value); };

  return <>
    <PageHeader eyebrow="ZEROING / OPTIC TOOLS" title="Put the rounds on zero" note="Fast, range-ready corrections for optic turrets and reticle measurements." />
    <div className="zeroing-tabs" aria-label="Zeroing tools"><button type="button" className={activeTool === "correction" ? "selected" : ""} aria-pressed={activeTool === "correction"} onClick={() => setActiveTool("correction")}>Click Calculation</button><button type="button" className={activeTool === "impact" ? "selected" : ""} aria-pressed={activeTool === "impact"} onClick={() => setActiveTool("impact")}>Impact Calculator</button></div>
    <div className="zeroing-grid">
      {activeTool === "correction" && <section className="zeroing-card" id="click-calculation" ref={correctionRef}>
        <div className="tool-heading"><div><span className="tool-kicker">01 / TURRET CLICKS</span><h2>Click Calculation</h2><p>Turn the measured impact into the optic adjustment required.</p></div><span className="tool-icon">⌾</span></div>
        <div className="zeroing-fields">
          <div className="field-group"><label>Distance to target</label><div className="input-pair"><input aria-label="Distance to target" type="number" min="0.01" step="any" inputMode="decimal" placeholder="100" value={correction.distance} onChange={event => setC("distance", event.target.value)} /><select aria-label="Distance unit" value={correction.distanceUnit} onChange={event => setC("distanceUnit", event.target.value as DistanceUnit)}><option value="yards">yards</option><option value="meters">meters</option></select></div></div>
          <div className="field-group"><label>Optic adjustment</label><div className="adjustment-grid"><div className="adjustment-unit"><span>Adjustment units</span><div className="unit-toggle" role="group" aria-label="Optic measurement system"><button type="button" className={correction.opticUnit === "MOA" ? "selected" : ""} onClick={() => { setSelectedOptic(""); setC("opticUnit", "MOA"); }}>MOA</button><button type="button" className={correction.opticUnit === "MIL" ? "selected" : ""} onClick={() => { setSelectedOptic(""); setC("opticUnit", "MIL"); }}>MRAD / MIL</button></div></div><label className="shared-click-input">Click value / turret<input aria-label="Shared optic click value" type="number" min="0.0001" step="any" inputMode="decimal" value={correction.elevationPerClick} onChange={event => { setSelectedOptic(""); setC("elevationPerClick", event.target.value); setC("windagePerClick", event.target.value); }} /></label><div className="quick-values"><span>Optic lookup</span><select className="quick-lookup" aria-label="Optic quick lookup" value={selectedOptic} onChange={event => applyQuickOptic(event.target.value)}><option value="">Select optic</option>{QUICK_OPTIC_VALUES.map(({ label }) => <option value={label} key={label}>{label}</option>)}</select></div></div></div>
          <fieldset className="offset-fieldset"><legend>Impact location</legend><div className="offset-row"><div className="offset-axis"><b>Vertical</b><span>Elevation</span></div><input aria-label="Vertical offset magnitude" type="number" min="0" step="any" inputMode="decimal" placeholder="0" value={correction.verticalMagnitude} onFocus={event => event.currentTarget.select()} onChange={event => setC("verticalMagnitude", event.target.value)} /><select aria-label="Vertical offset unit" value={correction.verticalUnit} onChange={event => setC("verticalUnit", event.target.value as OffsetUnit)}><option value="inches">inches</option><option value="centimeters">cm</option><option value="MOA">MOA</option><option value="mil">mil</option></select><select aria-label="Vertical impact direction" value={correction.verticalDirection} onChange={event => setC("verticalDirection", event.target.value as VerticalDirection)}><option value="LOW">LOW</option><option value="HIGH">HIGH</option></select></div><div className="offset-row"><div className="offset-axis"><b>Horizontal</b><span>Windage</span></div><input aria-label="Horizontal offset magnitude" type="number" min="0" step="any" inputMode="decimal" placeholder="0" value={correction.horizontalMagnitude} onFocus={event => event.currentTarget.select()} onChange={event => setC("horizontalMagnitude", event.target.value)} /><select aria-label="Horizontal offset unit" value={correction.horizontalUnit} onChange={event => setC("horizontalUnit", event.target.value as OffsetUnit)}><option value="inches">inches</option><option value="centimeters">cm</option><option value="MOA">MOA</option><option value="mil">mil</option></select><select aria-label="Horizontal impact direction" value={correction.horizontalDirection} onChange={event => setC("horizontalDirection", event.target.value as HorizontalDirection)}><option value="LEFT">LEFT</option><option value="RIGHT">RIGHT</option></select></div></fieldset>
        </div>
        {correctionError && <p className="zeroing-error" role="alert">{correctionError}</p>}<button className="primary calculate-button" type="button" onClick={calculateCorrection}>Calculate correction</button>
        {zeroResult && <CorrectionResults result={zeroResult} distance={n(correction.distance) ?? 100} distanceUnit={correction.distanceUnit} opticUnit={correction.opticUnit} elevationPerClick={n(correction.elevationPerClick) ?? 0} windagePerClick={n(correction.windagePerClick) ?? 0} />}
      </section>}

      {activeTool === "impact" && <section className="zeroing-card" id="impact-calculator" ref={correctionRef}>
        <div className="tool-heading"><div><span className="tool-kicker">02 / IMPACT MEASUREMENT</span><h2>Impact Calculator</h2><p>Convert a reticle reading into physical point-of-aim to point-of-impact distance.</p></div><span className="tool-icon">⊕</span></div>
        <div className="zeroing-fields">
          <div className="field-group"><label>Distance to target</label><div className="input-pair"><input aria-label="Reticle distance" type="number" min="0.01" step="any" inputMode="decimal" placeholder="100" value={reticle.distance} onChange={event => setR("distance", event.target.value)} /><select aria-label="Reticle distance unit" value={reticle.distanceUnit} onChange={event => setR("distanceUnit", event.target.value as DistanceUnit)}><option value="yards">yards</option><option value="meters">meters</option></select></div></div>
          <div className="field-group"><label>Reticle measurement</label><div className="unit-toggle" role="group" aria-label="Reticle measurement unit"><button type="button" className={reticle.reticleUnit === "MIL" ? "selected" : ""} onClick={() => setR("reticleUnit", "MIL")}>MIL</button><button type="button" className={reticle.reticleUnit === "MOA" ? "selected" : ""} onClick={() => setR("reticleUnit", "MOA")}>MOA</button></div></div>
          <div className="reticle-config-row"><div className="field-group"><label>Reticle type</label><div className="unit-toggle reticle-type-toggle" role="group" aria-label="Reticle type"><button type="button" className={reticle.reticleType === "FFP" ? "selected" : ""} aria-pressed={reticle.reticleType === "FFP"} onClick={() => setR("reticleType", "FFP")}>FFP</button><button type="button" className={reticle.reticleType === "SFP" ? "selected" : ""} aria-pressed={reticle.reticleType === "SFP"} onClick={() => setR("reticleType", "SFP")}>SFP</button></div></div><label className="magnification-input">Maximum magnification<input aria-label="Reticle maximum magnification" type="number" min="0.01" step="any" inputMode="decimal" value={reticle.magnification} onChange={event => setR("magnification", event.target.value)} placeholder="6x" /></label></div>
          {reticle.reticleType === "FFP" && <p className="info-note">FFP measurements remain valid at any magnification.</p>}{reticle.reticleType === "SFP" && <p className="info-note">Always use the maximum magnification on the optic.</p>}
          <fieldset className="offset-fieldset"><legend>Observed offset</legend><p className="field-help">One axis can be left blank.</p><div className="offset-row"><div className="offset-axis"><b>Horizontal</b><span>{reticle.reticleUnit} / windage</span></div><input aria-label="Observed horizontal offset" type="number" min="0" step="any" inputMode="decimal" placeholder="0" value={reticle.horizontalMagnitude} onFocus={event => event.currentTarget.select()} onChange={event => setR("horizontalMagnitude", event.target.value)} /><span className="unit-suffix">{unitLabel(reticle.reticleUnit)}</span><select aria-label="Observed horizontal direction" value={reticle.horizontalDirection} onChange={event => setR("horizontalDirection", event.target.value as HorizontalDirection)}><option value="LEFT">LEFT</option><option value="RIGHT">RIGHT</option></select></div><div className="offset-row"><div className="offset-axis"><b>Vertical</b><span>{reticle.reticleUnit} / elevation</span></div><input aria-label="Observed vertical offset" type="number" min="0" step="any" inputMode="decimal" placeholder="0" value={reticle.verticalMagnitude} onFocus={event => event.currentTarget.select()} onChange={event => setR("verticalMagnitude", event.target.value)} /><span className="unit-suffix">{unitLabel(reticle.reticleUnit)}</span><select aria-label="Observed vertical direction" value={reticle.verticalDirection} onChange={event => setR("verticalDirection", event.target.value as VerticalDirection)}><option value="LOW">LOW</option><option value="HIGH">HIGH</option></select></div></fieldset>
        </div>
        {reticleError && <p className="zeroing-error" role="alert">{reticleError}</p>}<button className="primary calculate-button" type="button" onClick={calculateReticle}>Calculate physical offset</button>
        {reticleResult && <ReticleResults result={reticleResult} distance={n(reticle.distance) ?? 100} distanceUnit={reticle.distanceUnit} reticleUnit={reticle.reticleUnit} reticleType={reticle.reticleType} onTransfer={transferToZeroing} />}
      </section>}
    </div>
    <details className="quick-reference"><summary>Quick Reference</summary><div><p><b>At 100 yards</b><br />1 MOA ≈ 1.047"<br />0.5 MOA ≈ 0.524"<br />1 MIL = 3.6"<br />0.1 MIL = 0.36"</p><p><b>At 100 meters</b><br />1 MIL = 10 cm<br />0.1 MIL = 1 cm</p></div></details>
  </>;
}

function PageHeader({ eyebrow, title, note }: { eyebrow: string; title: string; note: string }) { return <header className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{note}</p></div></header>; }


function CorrectionResults({ result, distance, distanceUnit, opticUnit, elevationPerClick, windagePerClick }: { result: ZeroingResult; distance: number; distanceUnit: DistanceUnit; opticUnit: AngularUnit; elevationPerClick: number; windagePerClick: number }) { return <section className="correction-result"><div className="result-heading"><span>REQUIRED CORRECTION</span><small>{distance} {distanceUnit} · {unitLabel(opticUnit)} / click</small></div><div className="result-grid"><ResultAxis title="Elevation" result={result.elevation} perClick={elevationPerClick} /><ResultAxis title="Windage" result={result.windage} perClick={windagePerClick} /></div><TargetPlot elevation={result.elevation} windage={result.windage} /></section>; }
function ResultAxis({ title, result, perClick }: { title: string; result: ZeroingResult["elevation"]; perClick: number }) { return <div className="result-axis"><small>{title}</small><b className={result.provided ? "" : "muted-result"}>{result.provided ? `${result.recommendedClicks} CLICKS ${result.adjustmentDirection}` : "NO ADJUSTMENT REQUIRED"}</b>{result.provided && <div className="technical-result"><span>Impact: {fixed(result.angularOffset, 2)} {unitLabel(result.angularUnit)}</span><span>Exact: {fixed(result.exactClicks)} clicks · {perClick} / click</span><span>Residual: ~{fixed(result.residual)} {result.residualUnit} {result.residualDirection}</span></div>}</div>; }
function TargetPlot({ elevation, windage }: { elevation: ZeroingResult["elevation"]; windage: ZeroingResult["windage"] }) { const x = windage.provided ? windage.adjustmentDirection === "RIGHT" ? 30 : 70 : 50; const y = elevation.provided ? elevation.adjustmentDirection === "UP" ? 70 : 30 : 50; return <div className="target-plot" aria-label="Impact location diagram"><span className="target-ring ring-one" /><span className="target-ring ring-two" /><span className="target-center" /><span className="target-point" style={{ left: `${x}%`, top: `${y}%` }} /></div>; }
function ReticleResults({ result, distance, distanceUnit, reticleUnit, reticleType, onTransfer }: { result: ReticleOffsetResult; distance: number; distanceUnit: DistanceUnit; reticleUnit: AngularUnit; reticleType: ReticleType; onTransfer: () => void }) { return <section className="reticle-result"><div className="result-heading"><span>PHYSICAL IMPACT OFFSET</span><small>{distance} {distanceUnit} · {reticleUnit}{reticleType === "SFP" ? " · max power" : ""}</small></div>{result.horizontal.provided && <ReticleAxis title="Horizontal" axis={result.horizontal} reticleUnit={reticleUnit} />}{result.vertical.provided && <ReticleAxis title="Vertical" axis={result.vertical} reticleUnit={reticleUnit} />}<button className="secondary use-zeroing" type="button" onClick={onTransfer}>Use for Zeroing</button></section>; }
function ReticleAxis({ title, axis, reticleUnit }: { title: string; axis: ReticleOffsetResult["horizontal"]; reticleUnit: AngularUnit }) { return <div className="reticle-axis"><div><small>{title}</small><b>{fixed(axis.angular, 2)} {unitLabel(reticleUnit)} {axis.direction}</b></div><strong>{fixed(axis.inches)}" {axis.direction}</strong><span>= {fixed(axis.centimeters)} cm {axis.direction}</span></div>; }
