import Dexie, { type EntityTable } from "dexie";
import type { AppSetting, Backup, Course, Drill, GoogleSheetsConnection, Run } from "./types";
class DrillTrackerDB extends Dexie { drills!: EntityTable<Drill,"id">; courses!: EntityTable<Course,"id">; runs!: EntityTable<Run,"id">; settings!: EntityTable<AppSetting,"key">; constructor(){ super("drill-tracker"); this.version(1).stores({drills:"id,name,active,favorite",courses:"id,name,active,favorite",runs:"id,drillId,courseId,timestamp"}); this.version(2).stores({drills:"id,name,active,favorite",courses:"id,name,active,favorite",runs:"id,drillId,courseId,timestamp,syncStatus",settings:"key"}); } }
export const db = new DrillTrackerDB();
const now = () => new Date().toISOString(); const id=(v:string)=>`seed-${v}`;
const drills: Drill[] = [
  {id:id("draw"),name:"Draw to First Shot",description:"Draw from holster and fire one accurate first shot.",maxHits:1,distance:"7 yd",libraryVisible:true,favorite:true,active:true,createdAt:now(),updatedAt:now()},
  {id:id("bill"),name:"Bill Drill",description:"From low ready, fire six rounds into the target as quickly as possible while maintaining acceptable hits.",maxHits:6,distance:"7 yd",libraryVisible:true,favorite:true,active:true,createdAt:now(),updatedAt:now()},
  {id:id("failure"),name:"Failure Drill",description:"Two shots to the body followed by one precise head shot.",maxHits:3,distance:"7 yd",libraryVisible:true,favorite:false,active:true,createdAt:now(),updatedAt:now()},
  {id:id("elpres"),name:"El Presidente",description:"Turn, draw, engage three targets, reload, and re-engage.",maxHits:12,distance:"10 yd",libraryVisible:true,favorite:false,active:true,createdAt:now(),updatedAt:now()},
];
const s=(name:string,maxTime:number,order:number)=>({id:id(`${name}-${maxTime}`),name,maxTime,order});
const qualificationDrill = (idPart:string,name:string,description:string,maxHits:number,distance:string):Drill => ({id:id(`qualification-${idPart}`),name,description,maxHits,distance,libraryVisible:false,favorite:false,active:true,createdAt:now(),updatedAt:now()});
const qualificationDrills: Drill[] = [
  qualificationDrill("rifle-bill","Rifle Bill Drill","Low ready. Fire 6 rifle rounds into the center A zone.",6,"7 yd"), qualificationDrill("pistol-bill","Pistol Bill Drill","Holster, hands at sides. Fire 6 pistol rounds into the center A zone.",6,"7 yd"), qualificationDrill("221-check","2-2-1 Check","High ready. Fire 2 rifle, 2 pistol, rifle check, then 1 credit-card rifle shot into the center A zone.",5,"7 yd"), qualificationDrill("room-clear","Room Clear","Start at 15 yd and move to 7 yd. Fire 3 rifle while moving to P1, run to P1, run to P2, then fire 2 rifle into the center A zone.",5,"15 yd to 7 yd"), qualificationDrill("222-transition","2-2-2 Transition","Start with the center target, then finish the remaining 2 and 2 rifle shots on the center A zone.",6,"15 yd"), qualificationDrill("1r3-rifle","1R3 Rifle","Fire 1 rifle, reload, then fire 3 rifle into the center A zone.",4,"15 yd"), qualificationDrill("1r3-pistol","1R3 Pistol","Fire 1 pistol, reload, then fire 3 pistol into the center A zone.",4,"15 yd"), qualificationDrill("knife","Knife Drill","Fire 4 pistol while retreating, run to 20 yd, then fire 1 pistol into the center A zone.",5,"7 yd to 20 yd"), qualificationDrill("contact","Contact Drill","Prone: 2 rifle. Stand: 2 rifle. The template lists 5 scoring shots into the center A zone.",5,"20 yd")
];
const qualificationTimes = [1.5,2,9,8,3,3.5,4.5,9,8];
const course: Course = {id:id("monthly"),name:"Qualification Course",description:"Nine-stage rifle and pistol qualification. Printed card: 235 total points, 188 points to pass. Stage point cells total 230; app uses each stage's listed shot count.",passCriteria:{minPoints:188},favorite:true,active:true,createdAt:now(),updatedAt:now(),entries:qualificationDrills.map((drill,order)=>({id:id(`qualification-entry-${order+1}`),drillId:drill.id,order,standards:[{id:id(`qualification-par-${order+1}`),name:"Par time",maxTime:qualificationTimes[order],order:0}]}))};
const manzanoDrill = (idPart:string,name:string,description:string,maxHits:number,distance:string):Drill => ({id:id(`manzano-${idPart}`),name,description,maxHits,distance,libraryVisible:false,favorite:false,active:true,createdAt:now(),updatedAt:now()});
const manzanoDrills: Drill[] = [
  manzanoDrill("p1","Pistol Stage 1 - 5 yd","1 round to the USPSA A zone.",1,"5 yd"), manzanoDrill("p2","Pistol Stage 2 - 5 yd","5 rounds to the USPSA A zone.",5,"5 yd"), manzanoDrill("p3","Pistol Stage 3 - 10 yd","5 rounds to the USPSA A zone.",5,"10 yd"), manzanoDrill("p4","Pistol Stage 4 - 10 yd","3 rounds to the USPSA A zone, slide-lock reload, then 3 rounds to the A zone.",6,"10 yd"), manzanoDrill("p5","Pistol Stage 5 - 25 yd","5 rounds to the USPSA A zone.",5,"25 yd"), manzanoDrill("p6","Pistol Stage 6 - 25 yd","1 round to the USPSA A zone.",1,"25 yd"),
  manzanoDrill("r1","Rifle Stage 1 - 5 yd","1 round to the USPSA A zone.",1,"5 yd"), manzanoDrill("r2","Rifle Stage 2 - 5 yd","5 rounds to the USPSA A zone.",5,"5 yd"), manzanoDrill("r3","Rifle Stage 3 - 10 yd","5 rounds to the USPSA A zone.",5,"10 yd"), manzanoDrill("r4","Rifle Stage 4 - 10 yd","3 rounds to the USPSA A zone, reload, then 3 rounds to the A zone.",6,"10 yd"), manzanoDrill("r5","Rifle Stage 5 - 25 yd","5 rounds to the USPSA A zone.",5,"25 yd"), manzanoDrill("r6","Rifle Stage 6 - 25 yd","1 round into the USPSA head box A zone.",1,"25 yd")
];
const manzanoCourse = (idPart:string,name:string,description:string,standardTimes:number[],demigodTimes:number[]):Course => ({id:id(`manzano-${idPart}`),name,description,passCriteria:{maxNonAlpha:5},favorite:true,active:true,createdAt:now(),updatedAt:now(),entries:standardTimes.map((standardTime,order)=>({id:id(`manzano-${idPart}-${order+1}`),drillId:id(`manzano-${idPart === "pistol" ? "p" : "r"}${order+1}`),order,standards:[{id:id(`manzano-${idPart}-${order+1}-demigod`),name:"Demigod",maxTime:demigodTimes[order],order:0},{id:id(`manzano-${idPart}-${order+1}-standard`),name:"Standard",maxTime:standardTime,order:1}]}))});
const manzanoCourses: Course[] = [manzanoCourse("pistol","Manzano Cold Start Pistol","Six-stage cold-start pistol course. All stages are scored on USPSA A-zone hits.",[1.5,2.5,5,7,7,2.5],[0.85,2,2.5,5,5,1.5]),manzanoCourse("rifle","Manzano Cold Start Rifle","Six-stage cold-start rifle course. Stage 6 uses the USPSA head-box A zone.",[0.85,2,2.5,5,5,1.5],[0.43,1,1.25,3.5,3.25,1.5])];
async function ensureQualification(){const marker="qualification-template-v3";if(await db.settings.get(marker))return;await db.transaction("rw",db.drills,db.courses,db.settings,async()=>{await db.drills.bulkPut(qualificationDrills);await db.courses.put(course);await db.settings.put({key:marker,value:true});});}
async function ensureManzano(){const marker="manzano-standards-v3";await db.transaction("rw",db.drills,db.courses,db.settings,async()=>{const [knownDrills,knownCourses,migrated]=await Promise.all([db.drills.bulkGet(manzanoDrills.map(drill=>drill.id)),db.courses.bulkGet(manzanoCourses.map(course=>course.id)),db.settings.get(marker)]);const newDrills=manzanoDrills.filter((_,index)=>!knownDrills[index]);const newCourses=manzanoCourses.filter((_,index)=>!knownCourses[index]);if(newDrills.length)await db.drills.bulkAdd(newDrills);if(newCourses.length)await db.courses.bulkAdd(newCourses);if(!migrated){await db.courses.bulkPut(manzanoCourses);await db.settings.put({key:marker,value:true});}});}
async function migrateCourseCriteria(){const marker="course-pass-criteria-v1";if(await db.settings.get(marker))return;await db.transaction("rw",db.courses,db.settings,async()=>{const courses=await db.courses.toArray();await db.courses.bulkPut(courses.map(course=>({ ...course, passCriteria:{ ...course.passCriteria, maxNonAlpha:course.passCriteria?.maxNonAlpha ?? (course.passCriteria?.requireAllAlpha ? undefined : course.maxTotalNonAlpha), minPoints:course.passCriteria?.minPoints ?? course.minTotalPoints } })));await db.settings.put({key:marker,value:true});});}
export async function ensureSeed(){ if(!await db.drills.count()) await db.transaction("rw",db.drills,db.courses,async()=>{await db.drills.bulkAdd(drills);await db.courses.add(course);}); await ensureQualification(); await ensureManzano(); await migrateCourseCriteria(); }
export async function snapshot():Promise<Backup>{const [allDrills,allCourses,allRuns,allSettings]=await Promise.all([db.drills.toArray(),db.courses.toArray(),db.runs.toArray(),db.settings.toArray()]);return {version:1,exportedAt:now(),drills:allDrills,courses:allCourses,runs:allRuns,settings:Object.fromEntries(allSettings.map(s=>[s.key,s.value]))};}
export async function replaceAll(data: Backup, replace: boolean){ const take=<T extends {id:string}>(existing:T[], incoming:T[])=>{const map=new Map(existing.map(x=>[x.id,x]));incoming.forEach(x=>map.set(x.id,x));return [...map.values()];}; const valid=(Array.isArray(data.drills)&&Array.isArray(data.courses)&&Array.isArray(data.runs));if(!valid)throw new Error("invalid"); if(replace){await db.transaction("rw",db.drills,db.courses,db.runs,()=>Promise.all([db.drills.clear(),db.courses.clear(),db.runs.clear()]).then(()=>Promise.all([db.drills.bulkAdd(data.drills),db.courses.bulkAdd(data.courses),db.runs.bulkAdd(data.runs)])));}else{const current=await snapshot();await db.transaction("rw",db.drills,db.courses,db.runs,()=>Promise.all([db.drills.bulkPut(take(current.drills,data.drills)),db.courses.bulkPut(take(current.courses,data.courses)),db.runs.bulkPut(take(current.runs,data.runs))]));}}
export async function getGoogleSheetsConnection(){return (await db.settings.get("googleSheets"))?.value as GoogleSheetsConnection | undefined;}
export async function saveGoogleSheetsConnection(connection:GoogleSheetsConnection){await db.settings.put({key:"googleSheets",value:connection});}
export async function clearGoogleSheetsConnection(){await db.settings.delete("googleSheets");}
export async function resetGoogleSheetRowPositions(){const runs=await db.runs.toArray();await db.runs.bulkPut(runs.map(run=>({...run,sheetRow:undefined,courseSheetRow:undefined})));}
