import Dexie, { type EntityTable } from "dexie";
import type { AppSetting, Backup, Course, Drill, GoogleSheetsConnection, Run } from "./types";
class DrillTrackerDB extends Dexie { drills!: EntityTable<Drill,"id">; courses!: EntityTable<Course,"id">; runs!: EntityTable<Run,"id">; settings!: EntityTable<AppSetting,"key">; constructor(){ super("drill-tracker"); this.version(1).stores({drills:"id,name,active,favorite",courses:"id,name,active,favorite",runs:"id,drillId,courseId,timestamp"}); this.version(2).stores({drills:"id,name,active,favorite",courses:"id,name,active,favorite",runs:"id,drillId,courseId,timestamp,syncStatus",settings:"key"}); } }
export const db = new DrillTrackerDB();
const now = () => new Date().toISOString(); const id=(v:string)=>`seed-${v}`;
const drills: Drill[] = [
  {id:id("draw"),name:"Draw to First Shot",description:"Draw from holster and fire one accurate first shot.",maxHits:1,distance:"7 yd",libraryVisible:true,favorite:true,active:true,createdAt:now(),updatedAt:now()},
  {id:id("bill"),name:"Bill Drill",description:"From low ready, fire six rounds into the target as quickly as possible while maintaining acceptable hits.",maxHits:6,distance:"7 yd",libraryVisible:true,favorite:true,active:true,createdAt:now(),updatedAt:now()},
  {id:id("failure"),name:"Failure Drill",description:"Two shots to the body followed by one precise head shot.",maxHits:3,distance:"7 yd",libraryVisible:true,favorite:false,active:true,createdAt:now(),updatedAt:now()},
  {id:id("elpres"),name:"El Presidente",description:"Turn, draw, engage three targets, reload, and re-engage.",maxHits:12,distance:"10 yd",libraryVisible:true,favorite:false,active:true,createdAt:now(),updatedAt:now()},
];
const s=(name:string,maxTime:number,order:number)=>({id:id(`${name}-${maxTime}`),name,maxTime,order});
const course: Course = {id:id("monthly"),name:"Monthly Qualification",description:"A reusable pistol performance assessment.",favorite:true,active:true,createdAt:now(),updatedAt:now(),entries:[{id:id("e1"),drillId:id("draw"),order:0,standards:[s("Expert",1.2,0),s("Advanced",1.6,1),s("Intermediate",2,2)]},{id:id("e2"),drillId:id("bill"),order:1,standards:[s("Expert",2,0),s("Advanced",2.5,1),s("Intermediate",3,2),s("Beginner",4,3)]},{id:id("e3"),drillId:id("failure"),order:2,standards:[s("Advanced",2.5,0),s("Intermediate",3.25,1)]},{id:id("e4"),drillId:id("elpres"),order:3,standards:[s("Advanced",8,0),s("Intermediate",10,1)]}]};
export async function ensureSeed(){ if(await db.drills.count()) return; await db.transaction("rw",db.drills,db.courses,async()=>{await db.drills.bulkAdd(drills);await db.courses.add(course);}); }
export async function snapshot():Promise<Backup>{const [allDrills,allCourses,allRuns,allSettings]=await Promise.all([db.drills.toArray(),db.courses.toArray(),db.runs.toArray(),db.settings.toArray()]);return {version:1,exportedAt:now(),drills:allDrills,courses:allCourses,runs:allRuns,settings:Object.fromEntries(allSettings.map(s=>[s.key,s.value]))};}
export async function replaceAll(data: Backup, replace: boolean){ const take=<T extends {id:string}>(existing:T[], incoming:T[])=>{const map=new Map(existing.map(x=>[x.id,x]));incoming.forEach(x=>map.set(x.id,x));return [...map.values()];}; const valid=(Array.isArray(data.drills)&&Array.isArray(data.courses)&&Array.isArray(data.runs));if(!valid)throw new Error("invalid"); if(replace){await db.transaction("rw",db.drills,db.courses,db.runs,()=>Promise.all([db.drills.clear(),db.courses.clear(),db.runs.clear()]).then(()=>Promise.all([db.drills.bulkAdd(data.drills),db.courses.bulkAdd(data.courses),db.runs.bulkAdd(data.runs)])));}else{const current=await snapshot();await db.transaction("rw",db.drills,db.courses,db.runs,()=>Promise.all([db.drills.bulkPut(take(current.drills,data.drills)),db.courses.bulkPut(take(current.courses,data.courses)),db.runs.bulkPut(take(current.runs,data.runs))]));}}
export async function getGoogleSheetsConnection(){return (await db.settings.get("googleSheets"))?.value as GoogleSheetsConnection | undefined;}
export async function saveGoogleSheetsConnection(connection:GoogleSheetsConnection){await db.settings.put({key:"googleSheets",value:connection});}
export async function clearGoogleSheetsConnection(){await db.settings.delete("googleSheets");}
